language: php

matrix:
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.3

  fast_finish: true

cache:
  directories:
    - vendor/bin/.phpunit

env:
  global:
    - COMPOSER_FLAGS=""

before_script:
  - |
    export COMPOSER_UP='composer update --dev --no-interaction --no-progress --no-suggest --ansi'
  - |
    if [[ $deps = low ]]; then
        $COMPOSER_UP --prefer-lowest --prefer-stable
    else
        $COMPOSER_UP
    fi
script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
